=begin comment

Demo Client for Passmeister Apple Wallet and Google Wallet API

[www.passmeister.com](https://www.passmeister.com).

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::PassApi');

my $api = WWW::SwaggerClient::PassApi->new();
isa_ok($api, 'WWW::SwaggerClient::PassApi');

#
# create_or_update_pass test
#
{
    my $pass_type_id = undef; # replace NULL with a proper value
    my $pass_id = undef; # replace NULL with a proper value
    my $result = $api->create_or_update_pass(pass_type_id => $pass_type_id, pass_id => $pass_id);
}

#
# delete_pass test
#
{
    my $pass_type_id = undef; # replace NULL with a proper value
    my $pass_id = undef; # replace NULL with a proper value
    my $result = $api->delete_pass(pass_type_id => $pass_type_id, pass_id => $pass_id);
}

#
# get_pass test
#
{
    my $pass_type_id = undef; # replace NULL with a proper value
    my $pass_id = undef; # replace NULL with a proper value
    my $result = $api->get_pass(pass_type_id => $pass_type_id, pass_id => $pass_id);
}

#
# pass_list test
#
{
    my $pass_type_id = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->pass_list(pass_type_id => $pass_type_id, page => $page, limit => $limit);
}

#
# pass_sync test
#
{
    my $pass_type_id = undef; # replace NULL with a proper value
    my $result = $api->pass_sync(pass_type_id => $pass_type_id);
}


1;
